name: untitled
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  kakao_flutter_sdk_user: ^1.9.5
  # kakaomap_webview: ^0.4.0
  image_picker: ^0.8.7+4
  dotted_border: ^2.0.0
  google_fonts: ^5.1.0

  http: ^1.2.2  # 최신 버전으로 업데이트
  kakao_flutter_sdk: ^1.9.6 
  file_picker: ^8.1.2
  kakao_map_plugin: ^0.3.1
  dio: ^5.7.0  # 최신 버전으로 업데이트
  dio_web_adapter: ^2.0.0  # 최신 버전으로 업데이트
  shared_preferences: ^2.3.2  # 최신 버전으로 업데이트
  # webview_flutter: ^4.9.0  # 최신 버전으로 업데이트
  # webview_flutter_android: ^3.16.7  # 최신 버전으로 업데이트
  share_plus: ^7.0.0

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker: ^10.0.4  # 최신 버전으로 업데이트
  leak_tracker_flutter_testing: ^3.0.3 # 최신 버전으로 업데이트

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
